### ISSUE TITLE
Accessibility Service Access Inside the Work Profile

### ISSUE THREAD

**Issue by ArunkumarAdhash** [googlesamples/android-testdpc#112]
Hi Team,

I have developed an application that was pushed into a work profile account, but in that, I can't able to give accessibility service for my app. it showing error toast-" **you are using this app outside of work profile** " and also it redirecting to personal profile accessibility setting. please address this.

**Comment by jscott1989** [comment]
This appears to be an issue with Android more generally rather than TestDPC.

If it's a bug, https://source.android.com/setup/contribute/report-bugs is the place to report it. If it's a general question about how Android works, somewhere like Stack Overflow would probably be better.

If this is an issue specific to TestDPC please re-open the bug and add simple reproduction steps.
