### ISSUE TITLE
It is impossible to install app using QR Code inside closed wifi network. 

### ISSUE THREAD

**Issue by exxbrain** [googlesamples/android-testdpc#122]
I downloaded example app from here: https://testdpc-latest-apk.appspot.com and used http://down-box.appspot.com/qr/nQB0tw7b with my own download path - something like http://192.168.1.12:8080/test.apk. It is my static page with example apk. 

When my wifi network is connected to the Internet - it's all ok: I tap 6 times on resetted Android 9 device and scan code - application is running ok. But when I disconnect from the Internet, installation process freezes on the next screen after QR Code scan for unlimited time. It is continues just after Internet connected again.

So Is it possible to use enrollment process using QR Code inside closed networks? And how to solve this issue?

**Comment by jscott1989** [comment]
I believe this should be possible - but this is a question about provisioning not specific to TestDPC.

If you have an approved DPC, could you open a partner bug about this?

**Comment by jscott1989** [comment]
Disclaimer: This is not officially supported and there is no guarantee future Android versions will keep supporting it. We also don't guarantee this will solve all of your closed network provisioning issues.

In order to support closed networks, you need to make EXTRA_PROVISIONING_WIFI_PAC_URL point to a dummy PAC file hosted on your local server, something like this - https://stackoverflow.com/questions/18757884/what-does-direct-in-a-pac-file-signifies

Note that for EXTRA_PROVISIONING_WIFI_PAC_URL to work, you need to specify a WiFi network to connect to as part of the provisioning process, using the other EXTRA_PROVISIONING_WIFI_* extras.
