### ISSUE TITLE
Reboot is not available on Marshmallow

### ISSUE THREAD

**Issue by amalChandran** [googlesamples/android-testdpc#7]
There is a reboot option in the test dpc app. This option is always disabled.

Can a device be rebooted by a device owner app? (Andorid M)

**Comment by hex539** [comment]
Amal,

Consider giving your issue reports useful names like "reboot is not available on Marshmallow" instead of filing them as "Not an issue". This helps other people with the same issue to find it. 

You can find the answer to this kind of question by
- reading the documentation on [DevicePolicyManager#reboot](https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#reboot(android.content.ComponentName)) (note the minimum API level - 24)
- or by looking at the source code to TestDPC ([PolicyManagementFragment.java](https://github.com/googlesamples/android-testdpc/blob/94da1d4/app/src/main/java/com/afwsamples/testdpc/policy/PolicyManagementFragment.java#L296))

We try to keep our documentation in good shape exactly so you don't have to keep asking questions like this. If you have read the documentation and still find something that's confusing, please raise an issue here or on AOSP and we will get it fixed ASAP.

**Comment by hex539** [comment]
Thanks. To clarify this particular case, it's an N API so unfortunately not available on Marshmallow.

**Comment by amalChandran** [comment]
Thanks for the quick response. Going forward, Ill have a thorough look at the doc before coming here.
